import esbuild from "esbuild";
import process from "process";
import { builtinModules } from 'node:module';
import { cpSync, mkdirSync } from 'node:fs';

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const devOutDir = "../funneler-api-dev";

const sharedOptions = {
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	treeShaking: true,
};

if (prod) {
	const context = await esbuild.context({
		...sharedOptions,
		outfile: "main.js",
		sourcemap: false,
		minify: true,
		define: { "IS_PRODUCTION": "true" },
	});
	await context.rebuild();
	process.exit(0);
} else {
	// Build production main.js for funneler-api
	const prodContext = await esbuild.context({
		...sharedOptions,
		outfile: "main.js",
		sourcemap: false,
		minify: true,
		define: { "IS_PRODUCTION": "true" },
	});
	await prodContext.rebuild();
	prodContext.dispose();

	// Watch dev build for funneler-api-dev
	mkdirSync(devOutDir, { recursive: true });
	cpSync("manifest-dev.json", `${devOutDir}/manifest.json`);

	const devContext = await esbuild.context({
		...sharedOptions,
		outfile: `${devOutDir}/main.js`,
		sourcemap: "inline",
		minify: false,
		define: { "IS_PRODUCTION": "false" },
	});
	await devContext.watch();
}
